ititle: Felicia Whalen # your name (or website title) here
title: Felicia Whalen
logo: "/images/hurricanes.jpg?raw=true" # your photo (or logo) here    

description: > # your text below (remove <br> elements if you don't need line breaks)    
  (hurricanes color coded by basin)   
  <br><br>
  A portfolio of some of my GIS projects.    
  
  I'm interested in cartography, spatial analysis, and ArcGIS apps.
  <br><br>
  
  <br><br>
  <ul>
  <li>  Personal Map projects that I have done for fun </li>    
  
  <br><br>
  
  <li>  School projects </li>       
  
  <!-- test -->
  </ul>
  
  <br><br>
  . . . a work in progress . . .
  <br><br>
  
  <br><br>
  <a href="https://storymaps.arcgis.com/stories/6e504b24afc543a896bd65f6e09555e8">View My Esri Story Map Portfolio</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
