ititle: Felicia Whalen # your name (or website title) here
title: Felicia Whalen
logo: "/images/hurricanes2.jpg?raw=true" # your photo (or logo) here    

description: > # your text below (remove <br> elements if you don't need line breaks)    
  <i>hurricanes color coded by basin</i>       
  <br><br>
    
  I have over four years' experience using the Esri suite of products; ArcMap, ArcPro, 
  ArcGIS Online, and many of their apps.     
  
  I <b>love</b> cartography, and have experience in spatial analysis,
  geocoding, georefferencing, geodatabase design, and Python scripting.    
  
  I have a Bachelor's degree in Computer Science from the University of Oklahoma,
  and am currently in my last year of OU's Masters in Geospatial Technologies 
  program.
  
  <br><br> 
  
   Scroll down on the right side to see a portfolio of some of my GIS projects. 
  <br><br>
  <ul>
  <li> A Community Service Project </li>    
  
  <li>  Personal Map projects that I have done for fun </li>    
  
 
  
  <li>  School projects </li>     
  
  <li>  Python Code Examples </li>
  
  <!-- test -->
  </ul>
  
  <!-- <br><br>  -->    
  <!--  . . . a work in progress . . . -->
  <!--  <br><br> -->
  
  <br><br>
  <a href="https://storymaps.arcgis.com/stories/6e504b24afc543a896bd65f6e09555e8">View My Esri Story Map Portfolio</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
